services:
  zulu-pro-app:
    image: ${DOCKER_IMAGE}
    container_name: zulu-pro-app
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      NODE_ENV: production
